### ISSUE TITLE
setValue

### ISSUE THREAD

**Issue by latiose** [Mobius1/Selectr#1]
I have a issue whit a function setValue my bowser send e error ReferenceError: _forEach is not defined

`<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>TEST</title>
		<link rel="stylesheet" type="text/css" href="Selectr/selectr.min.css">
		<script type="text/javascript" src="Selectr/selectr.min.js"></script>
	</head>
	<body>
		<select id="category" name=category multiple>
			<option value="0">Aucune categorie</option>
			<option value="1">Français</option>
			<option value="2">Biologie</option>
			<option value="3">Mathematique</option>
			<option value="4">Physique</option>
			<option value="5">Histoire Géographie</option>
			<option value="6">Autre</option>
			<option value="7">Informatique</option>
		</select>

		<button id="myButtonMulti" class="btn btn-primary">Set Values</button>

		<script type="text/javascript">
			var mySelectr = new Selectr(document.getElementById('category'), {
			searchable: true,
			width: 300
			});

			mySelectr.setValue(['1', '2', '3']);
			
		</script>
	</body>
</html>`

**Comment by Mobius1** [comment]
Thanks for bringing this to my attention. I've pushed a new release with a fix: [v1.0.7]https://github.com/Mobius1/Selectr/releases/tag/1.0.7
