### ISSUE TITLE
Dropdown doesn't calculate height of search field

### ISSUE THREAD

**Issue by AlexanderReiswich** [Mobius1/Selectr#10]
The open function seems to be based on the height of the selectr-options list and doesn't take the height of the search field into consideration:

var doInvert = _.elRect.top + _.elRect.height + _.optsRect.height > wh;

This results in a partially hidden dropdown box if it's close enough to the bottom of the window.

Additionally, because scrolling the page causes the dropdown to toggle, this makes it practically impossible to view the cut-off part of the dropdown.

It would be preferable to instead use the height of the selectr-options-container in the inversion calculation.

**Comment by Mobius1** [comment]
The part definitely needs overhauling and it's something I've been meaning to do.
