### ISSUE TITLE
Xss vulnerable

### ISSUE THREAD

**Issue by reno1979** [Mobius1/Selectr#102]
The util.createElement method uses the innerHTML method. 
Therefor I can execute a script like this : 

Input value for a taggable selectr instance : 

> `<img srx=‘x’ `onerror=‘alert(1)’>`

I’ll try to create a pull request as soon as possible. 

See 
https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

For more information

**Comment by reno1979** [comment]
see latest pull request update

**Comment by josdejong** [comment]
Good to see the issue is already on the radar :+1: 

I got it reported via https://app.snyk.io/test/npm/mobius1-selectr/2.4.8
