### ISSUE TITLE
Option to disable hiding on scroll/resize

### ISSUE THREAD

**Issue by AlexanderReiswich** [Mobius1/Selectr#11]
Selectr currently behaves much like a browser-default select box in that the dropdown hides on scroll and resize.

However, this isn't always ideal. It would be great to have an option, i.e. _preventClosing_ that can be activated in order to stop the dropdown from closing whenever you scroll.

A lot of people constantly have their finger on the scrolling wheel and it can get frustrating whenever the dropdown closes seemingly for no reason, just because you wanted to adjust the screen position.

**Comment by Mobius1** [comment]
Agreed. This is something that can be rectified whilst I'm working on #10
