### ISSUE TITLE
Method clear for one item

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [Mobius1/Selectr#113]
How can I clear just one item fron array, not all? Is that possible?

**Comment by trailsnail** [comment]
Which array do you mean, where you want to clear only one item?
The provided `clear` method clears all selections.
See [Documentation](https://github.com/Mobius1/Selectr/wiki/Public-Methods#clear)

**Comment by TchernyavskyDaniil** [comment]
It’snt works for me.
nvm, my pr accepted
