### ISSUE TITLE
Release 2.4.10 (Security Patch)?

### ISSUE THREAD

**Issue by adrian-enspired** [Mobius1/Selectr#119]
Is there an upcoming release `2.4.9`, or can we get one scheduled? 
In particular, would like to get #102 which is fixed in master but not available in a tagged version.

**Comment by adrian-enspired** [comment]
Should wait for https://github.com/Mobius1/Selectr/pull/120 and include it as well.

**Comment by adrian-enspired** [comment]
DANG IT I was too slow with #120 : (
so... release 2.4.10 ?

**Comment by adrian-enspired** [comment]
#121

**Comment by Mobius1** [comment]
All done, thanks, buddy 👍

**Comment by adrian-enspired** [comment]
thanks. and sorry for disorganization
