### ISSUE TITLE
form.reset() doesn't clear Selectr elements

### ISSUE THREAD

**Issue by ambrooks** [Mobius1/Selectr#13]
When you use the `form.reset()` method on a form element, it resets all inputs, and other form elements contained in the form to their default values. Any selectr-ised select boxes do not reset. You have to use the `selectr.reset()` method for each of them individually.

For reference: [MDN: HTMLFormElement.reset()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset)

Otherwise, Selectr.js works exactly how I expect. Thanks for making it!

**Comment by Mobius1** [comment]
Cheers, buddy. I'll push a fix for this tomorrow.
