### ISSUE TITLE
Problems while searching a large collection of data with pagination

### ISSUE THREAD

**Issue by luizalexandrew** [Mobius1/Selectr#15]
Hello,

I had a problem using search in selectr with pagination. With a small amount of data I did not have the problem, but when I used an array of 6000 data the selectr could not find the registry, only managing to find when I scroll until loading all the items.

![captura de tela de 2017-05-04 15-18-40](https://cloud.githubusercontent.com/assets/10445220/25718675/5d1f4858-30dd-11e7-80d4-590b7a769e9b.png)

**Comment by luizalexandrew** [comment]
When I scroll before the search until it reaches the item it is found.

The problem occore also in the example of pagination in the site, to reproduce research in the field by (playstation) and will not be found, clear the field and scroll until arriving at (playstation) and search that it will be found.

http://mobius.ovh/docs/selectr/pages/options

**Comment by Mobius1** [comment]
I'll get a fix out for this tomorrow. Thanks for bringing this to my attention 👍

**Comment by luizalexandrew** [comment]
Thank you very much @Mobius1
