### ISSUE TITLE
Cannot Create Selectr From Empty <select>

### ISSUE THREAD

**Issue by adrian-enspired** [Mobius1/Selectr#17]
Passing an empty `<select>` (no child `<option>`s) triggers an error:
```
Error: You don't have any options in your select!
```

Is this really a problem?  Why can Selectr not simply build an empty select list?

thanks for your time!

**Comment by Mobius1** [comment]
This will be fixed in the next update.

**Comment by adrian-enspired** [comment]
awesome, thanks.
