### ISSUE TITLE
Couple of issues and suggestions

### ISSUE THREAD

**Issue by labikmartin** [Mobius1/Selectr#21]
We had some several issues with this select. 

1.  **Empty select throws error** - I saw that there will be fix in next release

2. **Selectr prevents select to set its default value** - By default select sets its default value from first option child, therefore select has some valid value. But Selectr prevents this and instead of "some value" select has value of NULL which is a big problem in our occasion because our validation service doesnt allow NULL as valid value. So we added an option with value of "" ............ troubles continues in next point......

3. **Empty option breaks script** - If you add option with no value, Selectr throws error. See code below.

`
    <select id="test">  
    <option value=""></option>   
    <option value="yolo">John Doe</option>   
    </select>`

- I have fixed this by modifying line: 461 -> changed `(option.nodeName !== "OPTION" || !option.value)` to `(option.nodeName !== "OPTION" && !option.value)`    
 

4.  **Selectr doesn't emit "onchange" event for select** - It would be nice if Selectr could provide this by default. In case that somebody will need this, see code below   
`
    element.on('selectr.select', function(option) {
        let sel = option.parentNode;  
        if ("createEvent" in document) {  
          let evt = document.createEvent("HTMLEvents");  
          evt.initEvent("change", true, true);  
          sel.dispatchEvent(evt);    
        }  
        else {  
          sel.fireEvent("onchange");  
        }  
      });`  

5. **Enter new tag input placeholder** - It would be nice if we could change "Enter a tag..." placeholder for this input directly in Selectr options. If there is such option in Selectr already, then sorry, I didn't saw that :)

Those first 3 points made us suffer so badly, it took us 1 and a half day to figure everything out :D
But no hate sir! I think this library is great! 
Thank you for your effort, time and MIT license :)

**Comment by Mobius1** [comment]
Thanks for the suggestions and the bug reports, they help greatly.

I'm currently rewriting a lot of the library to fix other issues so I can easily fix the bugs and implement the options you've listed at the same time.

**Comment by Ugoku** [comment]
+1

Not having an `onchange` triggered by default made me choose [Choices](https://github.com/jshjohnson/Choices) over Selectr, despite Choices having a (slightly) larger filesize.
