### ISSUE TITLE
Highlight the top result when searching

### ISSUE THREAD

**Issue by binary-koan** [Mobius1/Selectr#26]
Hi,

I just noticed from playing around in the demo that you can't type to search and then press Enter to select the top search result (instead it selects whatever you'd hovered before you started searching). To me it would make sense to highlight the top search result when you enter text in the search box, unless your currently highlighted item is still in the list of search results - does that make sense?

Cheers! (and thanks for making this, I'm super impressed by how featureful and lightweight it is)

**Comment by Mobius1** [comment]
I'll push a fix for this later today. Thanks!
