### ISSUE TITLE
Safari first select value

### ISSUE THREAD

**Issue by lupett** [Mobius1/Selectr#28]
Hi, with safari when submit form, all unselected field take first option. What I can check for fix?

Also in safari desktop option are not under correct select but more right.

![error-safari](https://user-images.githubusercontent.com/14293996/27702790-7fe41f04-5d05-11e7-86f0-d99bc7b222a5.png)

**Comment by Mobius1** [comment]
Thanks for bringing this to my attention. I'll get a fix out ASAP.

**Comment by lupett** [comment]
Thanks. 
I'm available for testing fix, I've one site active with this problem.

**Comment by lupett** [comment]
More info

Portion of form

```
<form>
<select id="field-capelli" name="capelli" data-placeholder="Capelli">
                    <option value="bianchi" <?php if(isset($capelli) && $capelli) { echo $capelli == 'bianchi' ? 'selected' : ''; }?> >Bianchi</option>              
                    <option value="biondi" <?php if(isset($capelli) && $capelli) { echo $capelli == 'biondi' ? 'selected' : ''; }?> >Biondi</option>                     
</select>
</form>
```
Portion of JS

```
new Selectr('#field-capelli', {
      defaultSelected: false,
      allowDeselect: true,
      clearable: true,
      placeholder: "Capelli"
});

```

CSS for pagination

```
.selectr-container {  
    display: inline-flex;
    text-align: left;
    text-indent: 1px;
    margin: 5px 5px 7px 5px;
}
.selectr-selected {
    width: 100%;
    border: 1px solid #D2D2D2 !important;   
}
.selectr-placeholder {
    color: #B4B3B3;
}
@media screen and (min-width: 0) and (max-width: 540px) {
    .selectr-container {
        width: 100% !important;
    }
}
@media screen and (min-width:541px) and (max-width:818px) {
    .selectr-container {
        width: 47.3% !important;
    }
}
@media all and (min-width:1001px){
    .selectr-container {  
        width: 31% !important;
    }
}
```

**Comment by Mobius1** [comment]
Thanks, I'll see if I can get this fixed today/

**Comment by lupett** [comment]
Hi Mobius, any news? 
I don't want bother you, just to know if is possible to fix in little time or is more difficult. Because other solutions are not performing like this.

Thanks in advance!

**Comment by Mobius1** [comment]
Sorry, I forgot about this. Are you using iOS and/or macOS?

**Comment by lupett** [comment]
iOS and MacOS with Safari. 
If you leave me an email address I can send you more info and website link.

**Comment by Mobius1** [comment]
mobius1[at]gmx[dot]com

**Comment by lupett** [comment]
Thanks, sent!

**Comment by Mobius1** [comment]
Got this running on a Saucelabs VM on both OS X 10.12 and iOS 10.3 with Safari and both bugs are reproducable. I'll get this fixed ASAP.

**Comment by lupett** [comment]
Great news! Thanks

**Comment by Mobius1** [comment]
This should be fixed now. If there are any other problems related to the above bugs, please reopen this issue.
