### ISSUE TITLE
error: selectr need and element id to work

### ISSUE THREAD

**Issue by mckaygerhard** [Mobius1/Selectr#3]
2.2 *  seletr need and element id to work
this is when using exactly the documentation suggested, due the right way its `document.getelementById` in novice cases, althrought i dont nkow if its the right way 

documentation said that i need to do:

```
var mySelect = document.querySelector('select');
var mySelectr = new Selectr(mySelect);
```

but the document.querySelector('select') returns the firts input selector and this confuses novice users when try to use in and multi html **where the id and name input select are same, and are multiple selects inputs**

so documentation must be more clear, or are incorrect

**Comment by Mobius1** [comment]
As noted in my [previous reply](https://github.com/Mobius1/Selectr/issues/2), the documentation has been updated.

**Comment by mckaygerhard** [comment]
i'll lose due all i posted in #2
