### ISSUE TITLE
how to not overlaping other divs

### ISSUE THREAD

**Issue by mckaygerhard** [Mobius1/Selectr#4]
i have a dinamic div build on excution time on clien side , and also a select with your' implementation..

both inputs are the my firts, and then below the select with selectr implementation..

when i try to display the firts input , the div are redndered, but the "search" input of the selectr overlaping the others, see the picture, the firts input display a list, the second its the select with selectr implementation and overlaing the rendering of the firts:

![selectr-overlaping](https://cloud.githubusercontent.com/assets/1571724/23265904/991f2bd2-f9bc-11e6-9320-161e8189a612.png)

**Comment by Mobius1** [comment]
Use the following css rule:

```css
.selectr-selected {
	z-index: 1;
}
```

**Comment by mckaygerhard** [comment]
GREAT! THANKS. closed! thanks for u'r quick answer! good js library!
