### ISSUE TITLE
.search() Doesn't Return a Value

### ISSUE THREAD

**Issue by adrian-enspired** [Mobius1/Selectr#42]
> Search the available options for a string …returns an object of matched options.
https://github.com/Mobius1/Selectr/wiki/Public-Methods#searchquery

The `search()` method operates on the search box in-place and returns no value at all.  Is this not implemented yet? removed? wrong documentation?

If the documentation describes the desired behavior, I can work on a fix.

**Comment by Mobius1** [comment]
It got removed for some reason during a recent commit. Feel free to create a pull request with a fix if you want 👍
