### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by floq-design** [Mobius1/Selectr#6]
Hi
Just wanted to point out a typo on the docs in the Javascript initialisation:
http://mobius.ovh/docs/selectr/pages/installation#javascript
Docs read:
`new Selectr(document.getElementById('#mySelect'));`
should be:
`new Selectr(document.getElementById('mySelect'));`
Nice plugin!
Cheers

**Comment by Mobius1** [comment]
Cheers for letting me know! Fixed.

**Comment by floq-design** [comment]
Hey Karl
Fast work!
Afraid I've found a few more on events page:
http://mobius.ovh/docs/selectr/pages/events

All but the first event section has:
`selector.on('selector.[event]...`
which of course should be
`selector.on('selectr.[event]...`

Cheers

**Comment by Mobius1** [comment]
Cheers, buddy. This is what happens when you write documentation at 3am xD
