### ISSUE TITLE
add option not working

### ISSUE THREAD

**Issue by nightfury102497** [Mobius1/Selectr#65]
var selector2 = new Selectr("#someID");

	    selector2.addOption({
    value: "some-value",
    text: "Some Text"
});

**Comment by GawainLynch** [comment]
@nightfury102497 the function name is just [`add()`](https://github.com/Mobius1/Selectr/blob/2.4.1/src/selectr.js#L1618) and the documentation looks to just need an update :smile: 

This will work just fine:
```js
var selector2 = new Selectr("#someID");
selector2.add({
    value: "some-value",
    text: "Some Text"
});
```

**Comment by Mobius1** [comment]
Sorry, docs update 👍

**Comment by GawainLynch** [comment]
Thanks for a great library, and the docs update :+1:
