### ISSUE TITLE
IE 11 - Object doesn't support this action

### ISSUE THREAD

**Issue by v-braun** [Mobius1/Selectr#70]
Unfortunatley I use a minified version on our system.
Got that error on 
```
dispatchEvent(new Event("change"))
```
![image](https://user-images.githubusercontent.com/4738210/46064829-c9be7400-c170-11e8-8f01-2a8d658230a4.png)

I tried it in the IE console and I'm pretty sure that it is not the dispatchEvent call! I think it is the **new Event** constructor call.

See also here:
[dispatchEvent not working in IE11](https://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11)

**Comment by Mobius1** [comment]
Thanks. I'll push a fix out later today when I finish work.

**Comment by v-braun** [comment]
yes!
package.json:

``` js
....
"mobius1-selectr": "^2.4.3",
....
```

**Comment by Mobius1** [comment]
For some reason the npm version is referencing an old release.

**Comment by v-braun** [comment]
looks good! thx
