### ISSUE TITLE
Tag already in use message

### ISSUE THREAD

**Issue by reno1979** [Mobius1/Selectr#77]
First: Good job on Selectr!

We are using the just a small part of the current possibilities, and have no complaints ;) 

I do have a small request though... 
Could you make the message ‘That tag is allready in use’ configurable?

**Comment by Mobius1** [comment]
See the [`messages`](https://github.com/Mobius1/Selectr/wiki/Options#messages) option. Make sure you're using `v2.4.6`.

**Comment by reno1979** [comment]
V2.4.6 is not a release ? The beweest tag I van see is version 2.4.3

**Comment by Mobius1** [comment]
Here you go: https://github.com/Mobius1/Selectr/releases/tag/2.4.6

**Comment by reno1979** [comment]
Nice! Thank you!
