### ISSUE TITLE
Destroy the instance and recreate one

### ISSUE THREAD

**Issue by ciaoben** [Mobius1/Selectr#86]
I am coding a wrapper of this great library for React. I was wondering if there is a way to destroy an instance and re-initialize it with new settings. (I saw reset, but it reset it to the original. I need to make a new one with different options)

**Comment by Mobius1** [comment]
You can pass your new settings to the `render()` method after destroying.

```javascript
// instantiate
const instance = new Selectr("#mySelect", oldConfig);

// destroy
instance.destroy()

// render with new config
instance.render(newConfig)
```

**Comment by ciaoben** [comment]
@Mobius1 great, thank you!
