### ISSUE TITLE
Enhancement: Add tabindex.

### ISSUE THREAD

**Issue by mentinghfreightcenter** [Mobius1/Selectr#9]
How can you build a select box replacement that doesn't even tab focus? This plugin needs a lot of work!

**Comment by Mobius1** [comment]
A more constructive title would be helpful for other users.

**Comment by mentinghfreightcenter** [comment]
I don't know if this would be considered an enhancement.... all web browser select boxes support tabindex. Out of all the open source select boxes, yours is the most promising because of it's simple design & small filesize, but it definitely needs work to be considered production-ready. I wish I had the time to help.
