### ISSUE TITLE
Using optgroups in "data" options doesnt work on mobiles

### ISSUE THREAD

**Issue by rklabal** [Mobius1/Selectr#91]
When you push data with optgroups (exactly like you do in the examples on wiki), they display well on desktop, but are broken in the native mobile select. They are listed first and then all the options are displayed together afterwards,

Please see this pen: https://codepen.io/anon/pen/qQYxoV

Screenshot here: https://prnt.sc/lmdiiy

**Comment by trailsnail** [comment]
It happens here, but I don't have more time today to investigate further:
![image](https://user-images.githubusercontent.com/4742603/65625389-08794b00-dfcc-11e9-91b1-2d2f33d0faf5.png)

Code starts moving the options inside the `<select>`, although they are already rendered from `config.data`before click
![image](https://user-images.githubusercontent.com/4742603/65625517-3b234380-dfcc-11e9-9321-c7db2cf9ea0f.png)

Hope this will help a little bit
